# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: puppies

jobs:
# Please do not rename this job
  build-project:
    name: build puppies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
        run: npm run setup-production-app

      - name: Run script
        env:
          JWT_COOKIE_EXPIRES_IN: 90
          JWT_EXPIRES_IN: 90d
          JWT_SECRET: can-you-keep-a-secret-try-this-1
          MONGODB_URI: mongodb+srv://exagent957:mzFtRrTGjX63nUEt@cse341.9aujsue.mongodb.net/puppiesAPI?retryWrites=true&w=majority
          NODE_ENV: development
          NODE_VERSION: 20.5.1
        run: node app.js

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: deb46e16-9416-4f9a-ab11-cc3f65ef8a54
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/puppies/config.yaml
          action: upload
